name: Publish to Marketplace

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install -g vsce
          npm install

      - name: Publish
        run: vsce publish -p "$TOKEN"
        env:
          TOKEN: ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
