name: Publish to Marketplace

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run publish steps
        run: |
          npm install -g vsce
          npm install
          vsce login xarantolus <<< "$TOKEN"
          vsce publish -p "$TOKEN"
        env:
          TOKEN: ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
