name: Publish to Marketplace

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: |
          vsce login xarantolus <<< "$TOKEN"
          vsce publish
        env:
          TOKEN: ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
